[project]
name = "madica-chat-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
"langchain",
"langchain_community",
"langchain_huggingface",
"faiss_cpu",
"pypdf",
"flask",
"huggingface_hub",
"python-dotenv",
"sentence-transformers",
"langchain_groq"
]
